### ISSUE TITLE
Operator Overload Error of Postincrement and Preincrement.

### ISSUE THREAD

**Issue by felix-murray** [felix-murray/cs1c#5]
Current error when attempting to compile using clang version 11.0.0 on macOS:

`duplicate symbol 'operator++(Rank&)' in:
    /var/folders/f3/9th5vcm11_74xswlcz7j1mh80000gn/T/card-41f2c6.o
    /var/folders/f3/9th5vcm11_74xswlcz7j1mh80000gn/T/main-2d2ae1.o
duplicate symbol 'operator++(Rank&, int)' in:
    /var/folders/f3/9th5vcm11_74xswlcz7j1mh80000gn/T/card-41f2c6.o
    /var/folders/f3/9th5vcm11_74xswlcz7j1mh80000gn/T/main-2d2ae1.o
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Likely due to issue with overloading of post and pre increment operators as defined above `card` object definition in file `card.h`:
https://github.com/felix-murray/cs1c/blob/cdefe2116e348f375c2ea78c3cb469be4471e0e0/project-02/card.h#L31-L42

`Rank` is an enum defined in `card.h` as such:
https://github.com/felix-murray/cs1c/blob/cdefe2116e348f375c2ea78c3cb469be4471e0e0/project-02/card.h#L14-L29

**Comment by felix-murray** [comment]
Moved definition of `Rank& operator++(Rank& orig)` and `Rank operator++(Rank& orig, int)` to `card.cpp`.
